services:
  - type: web
    name: lithuanian-vocab
    runtime: node
    rootDir: lithuanian-vocab
    buildCommand: >
      npm install --prefix client &&
      npm run build --prefix client &&
      npm install --prefix server &&
      npm run build --prefix server
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: false
        value: 10000
